"""Ajout ArchiveStat

Revision ID: 4d9cc7dbea59
Revises: 9068e9ee0961
Create Date: 2025-07-26 20:24:35.752680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d9cc7dbea59'
down_revision = '9068e9ee0961'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archive_stat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('mois', sa.String(length=20), nullable=False),
    sa.Column('chiffre_affaires', sa.Float(), nullable=False),
    sa.Column('total_achats', sa.Float(), nullable=False),
    sa.Column('benefice', sa.Float(), nullable=False),
    sa.Column('marge', sa.Float(), nullable=False),
    sa.Column('nb_ventes', sa.Integer(), nullable=False),
    sa.Column('date_enregistrement', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('archive_stat')
    # ### end Alembic commands ###
