"""Ajout du champ mode_paiement à Recu

Revision ID: 515677f901ea
Revises: 4d9cc7dbea59
Create Date: 2025-07-26 22:15:36.524833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '515677f901ea'
down_revision = '4d9cc7dbea59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mode_paiement', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recu', schema=None) as batch_op:
        batch_op.drop_column('mode_paiement')

    # ### end Alembic commands ###
