"""Ajout du champ est_suspendu

Revision ID: 62515cf1169a
Revises: 515677f901ea
Create Date: 2025-11-08 12:28:57.601132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62515cf1169a'
down_revision = '515677f901ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ligne_recu')
    with op.batch_alter_table('ligne_vente', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.add_column(sa.Column('est_suspendu', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.drop_column('est_suspendu')

    with op.batch_alter_table('ligne_vente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    op.create_table('ligne_recu',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('recu_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('produit_nom', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('quantite', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('prix_unitaire', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['recu_id'], ['recu.id'], name=op.f('ligne_recu_recu_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ligne_recu_pkey'))
    )
    # ### end Alembic commands ###
