"""initial

Revision ID: 6f6a13716ce4
Revises: 
Create Date: 2025-07-25 12:13:14.348808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f6a13716ce4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demande_inscription',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom_utilisateur', sa.String(length=80), nullable=False),
    sa.Column('mot_de_passe', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('code_confirmation', sa.String(length=6), nullable=False),
    sa.Column('code_envoye_a', sa.DateTime(), nullable=True),
    sa.Column('date_demande', sa.DateTime(), nullable=True),
    sa.Column('valide', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('utilisateur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom_utilisateur', sa.String(length=80), nullable=False),
    sa.Column('mot_de_passe', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('nom_boutique', sa.String(length=100), nullable=True),
    sa.Column('adresse_boutique', sa.String(length=200), nullable=True),
    sa.Column('telephone_boutique', sa.String(length=50), nullable=True),
    sa.Column('logo', sa.String(length=200), nullable=True),
    sa.Column('code_pin', sa.String(length=10), nullable=True),
    sa.Column('code_confirmation', sa.String(length=6), nullable=True),
    sa.Column('code_envoye_a', sa.DateTime(), nullable=True),
    sa.Column('code_reset', sa.String(length=6), nullable=True),
    sa.Column('reset_envoye_a', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom_utilisateur')
    )
    op.create_table('fournisseur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('adresse', sa.Text(), nullable=True),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('supprime', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=30), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('montant_total', sa.Float(), nullable=False),
    sa.Column('supprime', sa.Boolean(), nullable=True),
    sa.Column('nom_client', sa.String(length=100), nullable=True),
    sa.Column('telephone_client', sa.String(length=20), nullable=True),
    sa.Column('montant_paye', sa.Float(), nullable=True),
    sa.Column('monnaie_rendue', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_table('statistique_mensuelle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('mois', sa.Integer(), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('chiffre_affaires', sa.Float(), nullable=True),
    sa.Column('nombre_ventes', sa.Integer(), nullable=True),
    sa.Column('date_enregistrement', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dette',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_nom', sa.String(length=100), nullable=False),
    sa.Column('client_telephone', sa.String(length=20), nullable=True),
    sa.Column('montant_total', sa.Float(), nullable=False),
    sa.Column('montant_rembourse', sa.Float(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_remboursement', sa.DateTime(), nullable=True),
    sa.Column('recu_id', sa.Integer(), nullable=True),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.Column('supprime', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['recu_id'], ['recu.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('prix_unitaire', sa.Float(), nullable=True),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('supprime', sa.Boolean(), nullable=True),
    sa.Column('fournisseur_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fournisseur_id'], ['fournisseur.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ligne_vente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recu_id', sa.Integer(), nullable=False),
    sa.Column('produit_id', sa.Integer(), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('prix_unitaire', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['produit_id'], ['produit.id'], ),
    sa.ForeignKeyConstraint(['recu_id'], ['recu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('remboursement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('date_remboursement', sa.DateTime(), nullable=True),
    sa.Column('dette_id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dette_id'], ['dette.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retour',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produit_id', sa.Integer(), nullable=False),
    sa.Column('recu_id', sa.Integer(), nullable=False),
    sa.Column('quantite_retournee', sa.Integer(), nullable=False),
    sa.Column('motif', sa.Text(), nullable=True),
    sa.Column('date_retour', sa.DateTime(), nullable=True),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.Column('supprime', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['produit_id'], ['produit.id'], ),
    sa.ForeignKeyConstraint(['recu_id'], ['recu.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produit_id', sa.Integer(), nullable=True),
    sa.Column('quantite', sa.Integer(), nullable=True),
    sa.Column('prix_unitaire', sa.Float(), nullable=True),
    sa.Column('date_vente', sa.DateTime(), nullable=True),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.Column('recu_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['produit_id'], ['produit.id'], ),
    sa.ForeignKeyConstraint(['recu_id'], ['recu.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vente')
    op.drop_table('retour')
    op.drop_table('remboursement')
    op.drop_table('ligne_vente')
    op.drop_table('produit')
    op.drop_table('dette')
    op.drop_table('statistique_mensuelle')
    op.drop_table('recu')
    op.drop_table('fournisseur')
    op.drop_table('utilisateur')
    op.drop_table('demande_inscription')
    # ### end Alembic commands ###
