"""ajout livraison dans recu

Revision ID: 87d6e817c875
Revises: 62515cf1169a
Create Date: 2026-04-03 12:47:40.866529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87d6e817c875'
down_revision = '62515cf1169a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adresse_livraison', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('prix_livraison', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recu', schema=None) as batch_op:
        batch_op.drop_column('prix_livraison')
        batch_op.drop_column('adresse_livraison')

    # ### end Alembic commands ###
