"""Ajout prix_achat et prix_vente

Revision ID: 9068e9ee0961
Revises: 6f6a13716ce4
Create Date: 2025-07-26 13:52:57.512959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9068e9ee0961'
down_revision = '6f6a13716ce4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prix_achat', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('prix_vente', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produit', schema=None) as batch_op:
        batch_op.drop_column('prix_vente')
        batch_op.drop_column('prix_achat')

    # ### end Alembic commands ###
