"""Ajout du champ supprime à produit et vente

Revision ID: b526f118a50a
Revises: 
Create Date: 2025-06-05 16:18:17.158134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b526f118a50a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supprime', sa.Boolean(), nullable=True))

    with op.batch_alter_table('vente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supprime', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vente', schema=None) as batch_op:
        batch_op.drop_column('supprime')

    with op.batch_alter_table('produit', schema=None) as batch_op:
        batch_op.drop_column('supprime')

    # ### end Alembic commands ###
